version: '3.7'
services:

    app:
      container_name: ${APP_NAME}
      build: .
      ports: 
        - ${PORT}:${PORT} 
      volumes:
        - app:/usr/src/app
      networks:
        - backend

    #postgre
    postgres:
        image: postgres:12
        # restart: always
        container_name: ${POSTGRES_CONTAINER_NAME}
        environment:
          - POSTGRES_USER=${POSTGRES_USER}
          - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
          - POSTGRES_DB=${POSTGRES_DB}
        logging:  
          options:
            max-size: 10m
            max-file: "3"
        ports:
          - '${POSTGRES_PORT}:${POSTGRES_PORT}'
        volumes: 
          - postgres-data:/var/lib/postgresql/data
        networks:
          - backend


    redis:
      image: redis:6.2-alpine
      container_name : ${REDIS_CONTAINER_NAME}
      networks:
        - backend
      ports:
          - '${REDIS_PORT}:${REDIS_PORT}'
      command: redis-server --requirepass ${REDIS_PASSWORD}
      volumes:
        - redis-data:/data



volumes: 
        app:
        postgres-data:
        redis-data:


networks: 
  backend:
    # driver: overlay
    # ipam:
    #   config:
    #   - subnet: 192.169.0.17/24
    driver: bridge
